# /.github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/getMovie:latest
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/getMovie:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag to YC Registry
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/getmovie:latest
